// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyghazxpbhavbavoywda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Z2hhenhwYmhhdmJhdm95d2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTk2MDMsImV4cCI6MjA3MTE3NTYwM30.P8qJKKWPtc6J1LQ0DxXwLDVPSpcaQ1txgW7dVpuPMrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});